app/core/urls.py
from django.urls import path
from app.core.views.category.views import *

app_name = 'core'

urlpatterns = [
    path('category/list/', CategoryListView.as_view(), name='CategoryListView')
]

app/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('core/', include('app.core.urls'))
]

app/core/models.py
from django.db import models
from datetime import datetime
from django.forms import model_to_dict

# Create your models here.

class Customer(models.Model):
    name = models.CharField(max_length=150)
    last_name = models.CharField(max_length=150)
    dni = models.CharField(max_length=20, unique=True)
    email = models.EmailField(max_length=254, unique=True)
    phone = models.CharField(max_length=20, blank=True)
    address = models.CharField(max_length=255, blank=True)
    sex = models.CharField(max_length=10, choices=[('M', 'Masculino'), ('F', 'Femenino')], default='M')

    def __str__(self):
        return f"{self.name} {self.last_name}"
    
    class Meta:
        verbose_name = "Cliente"
        verbose_name_plural = "Clientes"
        ordering = ["id"]

class Category(models.Model):
    name = models.CharField(max_length=150)

    def __str__(self):
        return self.name
    
    def toJSON(self):
        item = model_to_dict(self)
        return item
    
    class Meta:
        verbose_name = "Categoria"
        verbose_name_plural = "Categorias"
        ordering = ["id"]

class Product(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    name = models.CharField(max_length=150)
    image = models.ImageField(upload_to="products/images/", blank=True, null=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    stock = models.PositiveIntegerField(default=0)

    def __str__(self):
        return self.name
    
    class Meta:
        verbose_name = "Producto"
        verbose_name_plural = "Productos"
        ordering = ["id"]

class Sale(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE)
    date_sale = models.DateTimeField(default=datetime.now)
    subtotal = models.DecimalField(max_digits=10, decimal_places=2)
    iva = models.DecimalField(max_digits=10, decimal_places=2)
    total = models.DecimalField(max_digits=10, decimal_places=2)

    def __str__(self):
        return f"Venta {self.id} - {self.customer}"
    
    class Meta:
        verbose_name = "Venta"
        verbose_name_plural = "Ventas"
        ordering = ["id"]

class SaleDate(models.Model):
    sale = models.ForeignKey(Sale, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    amount = models.PositiveIntegerField(default=1)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    subtotal = models.DecimalField(max_digits=10, decimal_places=2)

    def __str__(self):
        return f"Detalle de Venta {self.id} - {self.sale} - {self.product}"
    
    class Meta:
        verbose_name = "Detalle de Venta"
        verbose_name_plural = "Detalles de Venta"
        ordering = ["id"]

app/core/views.py
from django.shortcuts import render
from django.http import HttpResponse, JsonResponse
from app.core.models import Category

# Create your views here.


def Category_list(request):
    data = {
        'title': 'Listado de Categorías',
        'categories': Category.objects.all(),
    }
    return render(request, 'index.html', data)

app/core/views/category/views.py
from urllib import request
from django import views
from django.shortcuts import render, redirect
from django.http import JsonResponse
from app.core.models import Category
from django.views.generic import ListView
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_exempt



# Create your views here.

class CategoryListView(ListView):
    model = Category
    template_name = 'category/list.html'

    @method_decorator(csrf_exempt)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        data = {}
        try:
            data = Category.objects.get(pk=request.POST['id']).toJSON()
        except Exception as e:
            data['error'] = str(e)
        return JsonResponse(data)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Listado de Categorías'
        context['object_list'] = Category.objects.all()
        return context

    

app/core/templates/category/list.html
{% extends "base_list.html" %}

{% block columns %}
  <tr>
    <th scope="col" style="width: 10%">ID</th>
    <th scope="col" style="width: 10%">Name</th>
    <th scope="col" style="width: 10%">Options</th>
  </tr>
{% endblock %}

{% block rows %}
  {% for c in object_list %}
  <tr>
    <td> {{ c.id }} </td>
    <td> {{ c.name }} </td>
    <td>
      <button type="button" class="btn btn-warning btn-xs btn-flat">
        <i class="fas fa-edit"></i>
      </button>
      <button type="button" class="btn btn-danger btn-xs btn-flat">
        <i class="fas fa-trash-alt"></i>
      </button>
    </td>
  </tr>
  {% endfor %}
{% endblock %}

app/templates/base.html
{% extends 'body.html' %}

{% block content_header %}
<div class='content'>
    <div class="container">
    </div>
</div>
{% endblock %}

app/templates/base_list.html
{% extends 'body.html' %}

{% load static %}

{% block head %}
    <link rel="stylesheet" href="{% static 'lib/DataTables/datatables.min.css' %}">
{% endblock %}

{% block content_header%}
   <div class="card card-default">
        <div class="card-header">
            <h3 class="card-title">
                <i class="fas fa-search"></i>
                {{ title }}
            </h3>
        </div>
        <div calss="card-body">
            <table class="table" id=data>
                <thead>
                    {% block columns %}
                    {% endblock %}
                </thead>
                <tbody>
                    {% block rows %}
                    {% endblock %}
                </tbody>
            </table>
        </div>
        <div class="card-footer">
            <button class="btn btn-primary btn-flat btnTest">
                <i class="fas fa-plus"></i> Nuevo Registro
            </button>
        </div>
    </div>
{% endblock %}

{% block javascript %}
    <script src="{% static 'lib/DataTables/datatables.min.js' %}"></script>
    <script>
        $(function () {
            $('#data').DataTable({
                responsive: true,
                autoWidth: false
            });

            $('.btnTest').on('click', function(){
                $.ajax({
                    url: '{% url 'core:CategoryListView'%}',
                    type: 'POST',
                    data: {id: 1},
                    dataType: 'json'
                }).done(function(data){
                    console.log(data);
                }).fail(function(data){
                    alert('Error')
                }).always(function(data){
                })
            });
        })
    </script>
{% endblock %}
    

app/templates/body.html
{% extends 'home.html' %}
{% load static %}

{% block content %}
<div class="content-header">
    <div class="container">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1 class="m-0 text-dark"> Bienvenido <small>Example 3.0</small></h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="#">Home</a></li>
                    <li class="breadcrumb-item"><a href="#">Layout</a></li>
                </ol>
            </div>
        </div>
    </div>
</div>

<div class="content">
    <div class="container">
        {% block content_header %}
        {% endblock %}
    </div>
    {% block javascript %}
        <script src="{% static 'lib/adminlte-3.0.4/plugins/jquery/jquery.min.js' %}"></script>
        <script src="{% static 'lib/datatables/datatables.min.js' %}"></script>
    {% endblock %}
</div>
{% endblock %}

app/templates/footer.html
<!-- Main Footer -->
<footer class="main-footer">
<!-- To the right -->
<div class="float-right d-none d-sm-inline">
    Anything you want
</div>
    <!-- Default to the left -->
<strong>Copyright &copy; 2014-2019 <a href="https://adminlte.io">AdminLTE.io</a>.</strong> All rights reserved.
</footer>

app/templates/header.html
{% load static%}
  <!-- Navbar -->
<nav class="main-header navbar navbar-expand-md navbar-light navbar-white">
  <div class="container">
    <a href="../../index3.html" class="navbar-brand">
      <img src="{% static 'lib/adminlte-3.0.4/img/AdminLTELogo.png' %}" alt="AdminLTE Logo" 
          class="brand-image img-circle elevation-3"
          style="opacity: .8">
      <span class="brand-text font-weight-light">Hades</span>
    </a>
    <button class="navbar-toggler order-1" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse order-3" id="navbarCollapse">
      <!-- Left navbar links -->
      <ul class="navbar-nav">
        <li class="nav-item">
          <a href="index3.html" class="nav-link">Home</a>
        </li>
        <li class="nav-item dropdown">
            <a id="dropdownSubMenu1" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" class="nav-link dropdown-toggle"><i class="fas fa-folder-open"></i> Mantenimientos</a>
            <ul aria-labelledby="dropdownSubMenu1" class="dropdown-menu border-0 shadow">
                <li><a href="#" class="dropdown-item"><i class="fas fa-fa-truck-loading"></i> Categorías</a></li>
                <li><a href="#" class="dropdown-item"><i class="fas fa-fa-boxes"></i> Productos</a></li>
                <li><a href="#" class="dropdown-item"><i class="fas fa-fa-users"></i> Clientes</a></li>
                <li><a href="#" class="dropdown-item"><i class="fas fa-fa-shopping-cart"></i> Ventas</a></li>
            </ul>
        </li>
      </ul>
    </div>
    <ul class="order-1 order-md-3 navbar-nav navbar-no-expand ml-auto">
      <!-- Messages Dropdown Menu -->
      <li class="nav-item dropdown">
        <a class="nav-link" data-toggle="dropdown" href="#">
          <i class="fas fa-comments"></i>
          <span class="badge badge-danger navbar-badge">15</span>
        </a>
        <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
          <span class="dropdown-header">15 Notifications</span>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <i class="fas fa-envelope mr-2"></i> 4 new messages
            <span class="float-right text-muted text-sm">3 mins</span>
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <i class="fas fa-users mr-2"></i> 8 friend requests
            <span class="float-right text-muted text-sm">12 hours</span>
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <i class="fas fa-file mr-2"></i> 3 new reports
            <span class="float-right text-muted text-sm">2 days</span>
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item dropdown-footer">See All Notifications</a>
        </div>
      </li>
    </ul>
  </div>
</nav>

app/templates/home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="x-ua-compatible" content="ie=edge">

  <title>{{ title }}</title>

  <!-- Font Awesome Icons -->
  <link rel="stylesheet" href="{% static 'lib/adminlte-3.0.4/plugins/fontawesome-free/css/all.min.css' %}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{% static 'lib/adminlte-3.0.4/css/adminlte.min.css' %}">
  <!-- Google Font: Source Sans Pro -->
  <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">

  {% block head %}

  {% endblock %}

</head>
<body class="hold-transition layout-top-nav">
  <div class="wrapper">

    {% include 'header.html' %}

    <div class="content-wrapper">
      {% block content %}

      {% endblock %}
    </div>

    {% include 'footer.html' %}

<!-- jQuery -->
<script src="{% static 'lib/adminlte-3.0.4/plugins/jquery/jquery.min.js' %}"></script>
<!-- Bootstrap 4 -->
<script src="{% static 'lib/adminlte-3.0.4/plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<!-- AdminLTE App -->
<script src="{% static 'lib/adminlte-3.0.4/js/adminlte.min.js' %}"></script>

{% block javascript %}

{% endblock %}
 
</body>
</html>